### ISSUE TITLE
Test SameBoy emulator

### ISSUE THREAD

**Issue by Luraktinus** [Gekkio/mooneye-gb#45]
https://sameboy.github.io/features/ claims that all mooneye-gb’s acceptance tests are passing, i would like an official test that is added in the README.md

**Comment by Gekkio** [comment]
Testing other emulators is way too time consuming, and there seems to be quite a lot of worthy emulators today.

So, I've instead decided to remove all other emulators from the comparison table. Emulators should do their own testing and report their own results.
