### ISSUE TITLE
Incorrect error message in stat_lyc_onoff test

### ISSUE THREAD

**Issue by zawata** [Gekkio/mooneye-gb#46]
https://github.com/Gekkio/mooneye-gb/blob/c14d750377b1ea926c191c21ef7808f47a765efa/tests/acceptance/ppu/stat_lyc_onoff.s#L116

I'm gonna guess that this line should be `fail_intr_round3` instead of `fail_intr_round2`

I'd make a PR but I'm on web and am too lazy to fork the project.

**Comment by Gekkio** [comment]
Thanks for the report! Fixed :smiley:
